#! /bin/sh

#-----------------------------------------------------------------------------
# WineLocale
#-----------------------------------------------------------------------------

all:
	@echo "Makefile: Available actions: install, uninstall"

# install the script
install:
	cp ../winelocale.py /usr/bin/winelocale.py
	chmod 755 /usr/bin/winelocale.py
	cp ../winelocale.svg /usr/share/pixmaps/winelocale.svg
	
